/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.sentry;

import org.appcelerator.kroll.KrollApplication;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollExceptionHandler;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollRuntime;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiMessenger;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;

import android.app.Activity;

import com.joshdholtz.sentry.Sentry;

@Kroll.module(name = "Sentry", id = "ti.sentry")
public class SentryModule extends KrollModule implements KrollExceptionHandler {
	final int MSG_OPEN_ERROR_DIALOG = 1000;
	boolean dialogShowing = false;

	public SentryModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		TiProperties appProperties = TiApplication.getInstance()
				.getAppProperties();
		String sentryDSN = appProperties.getString("SENTRY_DSN",
				"YOUR-SENTRY-DSN");
		Sentry.init(TiApplication.getInstance(), sentryDSN);
	}

	@Kroll.method
	public void captureMessage(String msg) {
		Sentry.captureMessage(msg);
	}

	@Kroll.method
	public void addHttpBreadcrumb(String url, String method, int result) {
		Sentry.addHttpBreadcrumb(url, method, result);
	}

	@Kroll.method
	public void addNavigationBreadcrumb(String event, String foo, String bar) {
		Sentry.addNavigationBreadcrumb(event, foo, bar);
	}

	@Kroll.method
	public void addBreadcrumb(String event, String payload) {
		Sentry.addBreadcrumb(event, payload);
	}

	@Kroll.method
	public void captureEvent(KrollDict kd) {
		Sentry.SentryEventBuilder builder = new Sentry.SentryEventBuilder();
		if (kd.containsKeyAndNotNull("message"))
			builder.setMessage(kd.getString("message"));
		if (kd.containsKeyAndNotNull("culprit"))
			builder.setCulprit(kd.getString("culprit"));
		if (kd.containsKeyAndNotNull("release"))
			builder.setRelease(kd.getString("release"));
		builder.setTimestamp(System.currentTimeMillis());
		Sentry.captureEvent(builder);
	}

	protected void handleError(ExceptionMessage error) {
		KrollDict dict = new KrollDict();
		dict.put("title", error.title);
		dict.put("message", error.message);
		dict.put("sourceName", error.sourceName);
		dict.put("line", error.line);
		dict.put("lineSource", error.lineSource);
		dict.put("lineOffset", error.lineOffset);
		TiApplication.getInstance().fireAppEvent("uncaughtException", dict);
		TiApplication tiApplication = TiApplication.getInstance();
		if (tiApplication.getDeployType().equals(
				TiApplication.DEPLOY_TYPE_PRODUCTION)) {
			return;
		}

	}

	@Override
	public void handleException(ExceptionMessage error) {
		if (TiApplication.isUIThread()) {
			handleError(error);
		} else {
			TiMessenger.sendBlockingMainMessage(
					mainHandler.obtainMessage(MSG_OPEN_ERROR_DIALOG), error);
		}

	}

}
