/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.sentry;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollExceptionHandler;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;

import com.joshdholtz.sentry.Sentry;

@Kroll.module(name = "Sentry", id = "ti.sentry")
public class SentryModule extends KrollModule implements KrollExceptionHandler {

	public SentryModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		TiProperties appProperties = TiApplication.getInstance()
				.getAppProperties();
		String sentryDSN = appProperties.getString("SENTRY_DSN",
				"YOUR-SENTRY-DSN");
		Sentry.init(TiApplication.getInstance(), sentryDSN);
	}

	@Kroll.method
	public void captureMessage(String msg) {
		Sentry.captureMessage(msg);
	}

	@Kroll.method
	public void addHttpBreadcrumb(String url, String method, int result) {
		Sentry.addHttpBreadcrumb(url, method, result);
	}

	@Kroll.method
	public void addNavigationBreadcrumb(String event, String foo, String bar) {
		Sentry.addNavigationBreadcrumb(event, foo, bar);
	}

	@Kroll.method
	public void addBreadcrumb(String event, String payload) {
		Sentry.addBreadcrumb(event, payload);
	}

	@Kroll.method
	public void captureEvent(KrollDict kd) {
		Sentry.SentryEventBuilder builder = new Sentry.SentryEventBuilder();
		if (kd.containsKeyAndNotNull("message"))
			builder.setMessage(kd.getString("message"));
		if (kd.containsKeyAndNotNull("culprit"))
			builder.setCulprit(kd.getString("culprit"));
		if (kd.containsKeyAndNotNull("release"))
			builder.setRelease(kd.getString("release"));
		builder.setTimestamp(System.currentTimeMillis());
		Sentry.captureEvent(builder);
	}

}
