#source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods',
:integrate_targets => false
platform :ios, '8.0'
#use_frameworks!

target 'tisentry' do
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '3.11.1'
end
